name: saas-starter-db

services:
  postgres:
    image: postgres:16-alpine
    container_name: saas-starter-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB:-saas_db}
    volumes:
      - saas_starter_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - saas-starter-network

  stripe-cli:
    image: stripe/stripe-cli
    env_file:
      - ./.env
    command: "listen --forward-to host.docker.internal:${PORT}/api/stripe/webhook"

networks:
  saas-starter-network:
    name: saas-starter-network
    driver: bridge

volumes:
  saas_starter_postgres_data:
    name: saas-starter-postgres-data
